In [1]:
import pandas as pd

data = pd.read_csv("../Data/cleaned_fraud_dataset.csv")

print(data.shape)
print(data.columns.tolist())
data.head()

(10000, 19)
['transaction_amount', 'login_attempts', 'device_risk_score', 'transfer_frequency', 'anomaly_score', 'account_age_days', 'transaction_time_hour', 'failed_transactions_last_30d', 'avg_monthly_balance', 'daily_transaction_count', 'geo_distance_km', 'session_duration_minutes', 'transaction_velocity_score', 'payment_channel', 'authentication_type', 'card_present_flag', 'international_transaction_flag', 'suspicious_ip_flag', 'fraud_flag']

,transaction_amount,login_attempts,device_risk_score,transfer_frequency,anomaly_score,account_age_days,transaction_time_hour,failed_transactions_last_30d,avg_monthly_balance,daily_transaction_count,geo_distance_km,session_duration_minutes,transaction_velocity_score,payment_channel,authentication_type,card_present_flag,international_transaction_flag,suspicious_ip_flag,fraud_flag
0,17829.01,4,12.0,13,0.37,2354,22,25,112760.07,63,3189,92,71.8,POS Terminal,OTP,1,1,1,0
1,16401.83,1,34.3,17,0.26,3181,17,15,118899.52,83,839,63,11.8,Web Banking,Biometric,0,0,1,0
2,9678.29,8,67.8,39,0.15,1390,3,2,408168.98,9,3938,80,35.7,ATM,OTP,1,0,1,0
3,19013.38,5,17.8,42,0.55,3716,16,6,80771.69,78,11111,11,74.8,Mobile App,OTP,1,1,0,0
4,13834.95,3,88.9,63,0.24,4694,16,10,382265.32,17,3171,87,0.0,Mobile App,OTP,1,0,0,0

In [2]:
import pandas as pd

# Load the clean dataset from preprocessing
data = pd.read_csv("../Data/cleaned_fraud_dataset.csv")

# Create a copy that represents the dataset after EDA
data.to_csv("../Data/eda_completed_dataset.csv", index=False)

data.head()

,transaction_amount,login_attempts,device_risk_score,transfer_frequency,anomaly_score,account_age_days,transaction_time_hour,failed_transactions_last_30d,avg_monthly_balance,daily_transaction_count,geo_distance_km,session_duration_minutes,transaction_velocity_score,payment_channel,authentication_type,card_present_flag,international_transaction_flag,suspicious_ip_flag,fraud_flag
0,17829.01,4,12.0,13,0.37,2354,22,25,112760.07,63,3189,92,71.8,POS Terminal,OTP,1,1,1,0
1,16401.83,1,34.3,17,0.26,3181,17,15,118899.52,83,839,63,11.8,Web Banking,Biometric,0,0,1,0
2,9678.29,8,67.8,39,0.15,1390,3,2,408168.98,9,3938,80,35.7,ATM,OTP,1,0,1,0
3,19013.38,5,17.8,42,0.55,3716,16,6,80771.69,78,11111,11,74.8,Mobile App,OTP,1,1,0,0
4,13834.95,3,88.9,63,0.24,4694,16,10,382265.32,17,3171,87,0.0,Mobile App,OTP,1,0,0,0

In [3]:
#identify the categorical and numerical feature 
#identify the target variable
data.info()
data.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 19 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   transaction_amount              10000 non-null  float64
 1   login_attempts                  10000 non-null  int64
 2   device_risk_score               10000 non-null  float64
 3   transfer_frequency              10000 non-null  int64
 4   anomaly_score                   10000 non-null  float64
 5   account_age_days                10000 non-null  int64
 6   transaction_time_hour           10000 non-null  int64
 7   failed_transactions_last_30d    10000 non-null  int64
 8   avg_monthly_balance             10000 non-null  float64
 9   daily_transaction_count         10000 non-null  int64
 10  geo_distance_km                 10000 non-null  int64
 11  session_duration_minutes        10000 non-null  int64
 12  transaction_velocity_score      10000 non-null  float64
 13  payment_channel                 10000 non-null  object
 14  authentication_type             10000 non-null  object
 15  card_present_flag               10000 non-null  int64
 16  international_transaction_flag  10000 non-null  int64
 17  suspicious_ip_flag              10000 non-null  int64
 18  fraud_flag                      10000 non-null  int64
dtypes: float64(5), int64(12), object(2)
memory usage: 1.4+ MB

Index(['transaction_amount', 'login_attempts', 'device_risk_score',
       'transfer_frequency', 'anomaly_score', 'account_age_days',
       'transaction_time_hour', 'failed_transactions_last_30d',
       'avg_monthly_balance', 'daily_transaction_count', 'geo_distance_km',
       'session_duration_minutes', 'transaction_velocity_score',
       'payment_channel', 'authentication_type', 'card_present_flag',
       'international_transaction_flag', 'suspicious_ip_flag', 'fraud_flag'],
      dtype='object')

In [4]:
#new account indicator
data['new_account'] = (  data['account_age_days'] < 180).astype(int)

In [5]:
numerical_cols = data.select_dtypes(include=['int64', 'float64']).columns
categorical_cols = data.select_dtypes(include=['object']).columns

print("Numerical:", numerical_cols)
print("Categorical:", categorical_cols)

Numerical: Index(['transaction_amount', 'login_attempts', 'device_risk_score',
       'transfer_frequency', 'anomaly_score', 'account_age_days',
       'transaction_time_hour', 'failed_transactions_last_30d',
       'avg_monthly_balance', 'daily_transaction_count', 'geo_distance_km',
       'session_duration_minutes', 'transaction_velocity_score',
       'card_present_flag', 'international_transaction_flag',
       'suspicious_ip_flag', 'fraud_flag', 'new_account'],
      dtype='object')
Categorical: Index(['payment_channel', 'authentication_type'], dtype='object')

HIGH TRANSACTION AMOUNT

In [7]:
# Create feature
data['high_value_transaction'] = (
    data['transaction_amount'] >
    data['transaction_amount'].quantile(0.75)
).astype(int)

# Verify feature
print("High Value Transaction")
print(data['high_value_transaction'].value_counts())

High Value Transaction
high_value_transaction
0    7500
1    2500
Name: count, dtype: int64

In [12]:
print(pd.crosstab(data['high_value_transaction'], data['fraud_flag']))

fraud_flag                 0    1
high_value_transaction
0                       6582  918
1                       2167  333

HIGH LOGIN ATTEMPT

In [8]:
# Create feature
data['high_login_attempts'] = (
    data['login_attempts'] >= 3
).astype(int)

# Verify feature
print("\nHigh Login Attempts")
print(data['high_login_attempts'].value_counts())

High Login Attempts
high_login_attempts
1    8288
0    1712
Name: count, dtype: int64

In [13]:
data['high_login_attempts'] = (
    data['login_attempts'] > data['login_attempts'].quantile(0.75)
).astype(int)

print("High Login Attempts")
print(data['high_login_attempts'].value_counts())

High Login Attempts
high_login_attempts
0    7580
1    2420
Name: count, dtype: int64

In [11]:
print(data['login_attempts'].describe())
print(data['login_attempts'].value_counts().sort_index())

count    10000.000000
mean         6.438900
std          3.453558
min          1.000000
25%          3.000000
50%          6.000000
75%          9.000000
max         12.000000
Name: login_attempts, dtype: float64
login_attempts
1     834
2     878
3     898
4     813
5     849
6     771
7     823
8     805
9     909
10    800
11    840
12    780
Name: count, dtype: int64

High Velocity Transaction

In [9]:
# Create feature
data['high_velocity'] = (
    data['transaction_velocity_score'] >
    data['transaction_velocity_score'].quantile(0.75)
).astype(int)

# Verify feature
print("\nHigh Velocity")
print(data['high_velocity'].value_counts())

High Velocity
high_velocity
0    7504
1    2496
Name: count, dtype: int64

NIGHT TRASNACTION

In [10]:
# Create feature
data['night_transaction'] = (
    (data['transaction_time_hour'] >= 22) |
    (data['transaction_time_hour'] <= 5)
).astype(int)

# Verify feature
print("\nNight Transaction")
print(data['night_transaction'].value_counts())

Night Transaction
night_transaction
0    6658
1    3342
Name: count, dtype: int64

Far Distance Transaction

This feature identifies transactions occurring at unusually large geographical distances (top 25% of distances). Transactions taking place far from a customer's typical location may indicate fraudulent activity.

In [ ]:
# Create feature
data['far_distance_transaction'] = (
    data['geo_distance_km'] >
    data['geo_distance_km'].quantile(0.75)).astype(int)

# Verify feature
print("Far Distance Transaction")
print(data['far_distance_transaction'].value_counts())

Far Distance Transaction
far_distance_transaction
0    7500
1    2500
Name: count, dtype: int64

In [15]:
print(pd.crosstab(
    data['far_distance_transaction'],
    data['fraud_flag']))

fraud_flag                   0    1
far_distance_transaction
0                         6539  961
1                         2210  290

High Device Risk

 This feature flags transactions originating from devices with risk scores in the top 25% of the dataset. High-risk devices may have a greater likelihood of being associated with fraudulent transactions.

In [ ]:
# Create feature
data['high_device_risk'] = (
    data['device_risk_score'] >
    data['device_risk_score'].quantile(0.75)).astype(int)

# Verify feature
print("High Device Risk")
print(data['high_device_risk'].value_counts())

High Device Risk
high_device_risk
0    7502
1    2498
Name: count, dtype: int64

In [ ]:
#checking if the new features are correlated with the target variable
print(pd.crosstab(
    data['high_device_risk'],
    data['fraud_flag']))

fraud_flag           0    1
high_device_risk
0                 6565  937
1                 2184  314